export const ADD_TO_BASKET = "ADD_TO_BASKET";
export const REMOVE_FROM_BASKET = "REMOVE_FROM_BASKET";
export const UPDATE_QUANTITY = "UPDATE_QUANTITY";
export const OPEN_BASKET_MODAL = "OPEN_BASKET_MODAL";
export const CLOSE_BASKET_MODAL = "CLOSE_BASKET_MODAL";
