export const FETCH_PRODUCTS_HOME_SUCCESS = "FETCH_PRODUCTS_HOME_SUCCESS";
export const FETCH_PRODUCTS_HOME_ERROR = "FETCH_PRODUCTS_HOME_ERROR";
export const FETCH_PRODUCTS_HOME_LOADING = "FETCH_PRODUCTS_HOME_LOADING";
