export const FETCH_SEARCH_PRODUCT_SUCCESS = "FETCH_SEARCH_PRODUCT_SUCCESS";
export const FETCH_SEARCH_PRODUCT_ERROR = "FETCH_SEARCH_PRODUCT_ERROR";
export const FETCH_SEARCH_PRODUCT_LOADING = "FETCH_SEARCH_PRODUCT_LOADING";
